for_action_testing = [
    "draw_5",
    "draw_4",
    "draw_2",
    "play_2",
    "draw_3",
    "play_4",
    "play_3",

    "lullaby",
    "milk_and_cookies",
    "the_minds_eye",
    "night_and_day",
    "party_time",

    "rocket_to_the_moon",
    "squishy_chocolate",
    "time_is_money",
    "toast",
    "turn_it_up",
    "winning_the_lottery",

    "trash_a_new_rule",
    "draw_3_play_2_of_them",
    "zap_a_card",
    "everybody_gets_1",
    "lets_do_that_again"
]

simple_fluxx_deck = [
    # Rules - Draw/Play/Limits
    "hand_limit_2",
    "hand_limit_1",
    "hand_limit_0",
    "keeper_limit_4",
    "keeper_limit_3",
    "keeper_limit_2",
    "draw_5",
    "draw_4",
    "draw_2",
    "play_2",
    "draw_3",
    "play_4",
    "play_3",

    # Keepers
    "the_sun",
    "the_party",
    "music",
    "dreams",
    "love",
    "peace",
    "sleep",
    "the_brain",
    "bread",
    "chocolate",
    "cookies",
    "milk",
    "time",
    "money",
    "the_eye",
    "the_moon",
    "the_rocket",
    "the_toaster",
    "television",

    # Goals
    "the_appliances",
    "baked_goods",
    "bed_time",
    "bread_and_chocolate",
    "cant_buy_me_love",
    "chocolate_cookies",
    "chocolate_milk",
    "day_dreams",
    "dreamland",
    "the_eye_of_the_beholder",
    "great_theme_song",
    "hearts_and_minds",
    "hippyism",
    "lullaby",
    "milk_and_cookies",
    "the_minds_eye",
    "night_and_day",
    "party_time",
    "rocket_science",
    "rocket_to_the_moon",
    "squishy_chocolate",
    "time_is_money",
    "toast",
    "turn_it_up",
    "winning_the_lottery",
    "world_peace",
    "5_keepers",
    "10_cards_in_hand",
    "the_brain_no_tv",
    "party_snacks",
]

base_deck = [
    # Rules - Draw/Play/Limits
    "hand_limit_2",
    "hand_limit_1",
    "hand_limit_0",
    "keeper_limit_4",
    "keeper_limit_3",
    "keeper_limit_2",
    "draw_5",
    "draw_4",
    "draw_2",
    "play_2",
    "draw_3",
    "play_4",
    "play_3",

    # Keepers
    "the_sun",
    "the_party",
    "music",
    "dreams",
    "love",
    "peace",
    "sleep",
    "the_brain",
    "bread",
    "chocolate",
    "cookies",
    "milk",
    "time",
    "money",
    "the_eye",
    "the_moon",
    "the_rocket",
    "the_toaster",
    "television",

    # Goals
    "the_appliances",
    "baked_goods",
    "bed_time",
    "bread_and_chocolate",
    "cant_buy_me_love",
    "chocolate_cookies",
    "chocolate_milk",
    "day_dreams",
    "dreamland",
    "the_eye_of_the_beholder",
    "great_theme_song",
    "hearts_and_minds",
    "hippyism",
    "lullaby",
    "milk_and_cookies",
    "the_minds_eye",
    "night_and_day",
    "party_time",
    "rocket_science",
    "rocket_to_the_moon",
    "squishy_chocolate",
    "time_is_money",
    "toast",
    "turn_it_up",
    "winning_the_lottery",
    "world_peace",
    "5_keepers",
    "10_cards_in_hand",
    "the_brain_no_tv",
    "party_snacks",

    # Actions
    "use_what_you_take",
    "zap_a_card",
    "trash_a_new_rule",
    "trash_a_keeper",
    "trade_hands",
    "todays_special",
    "draw_2_and_use_em",
    "draw_3_play_2_of_them",
    "steal_a_keeper",
    "share_the_wealth",
    "rules_reset",
    "rock_paper_scissors_showdown",
    "random_tax",
    "no_limits",
    "lets_simplify",
    "lets_do_that_again",
    "jackpot",
    "exchange_keepers",
    "empty_the_trash",
    "discard_and_draw",
    "take_another_turn",
    "rotate_hands",
    "everybody_gets_1",

    # Free Action/Complex Rules
    "mystery_play",
    "swap_plays_for_draws",
    "get_on_with_it",
    "recycling",
    "goal_mill",
    "play_all",
    "play_all_but_1",
    "no_hand_bonus",
    "party_bonus",
    "poor_bonus",
    "rich_bonus",
    "double_agenda",
    "first_play_random",
    "inflation",
]