expanded_deck = [
    # Basic rules
    "hand_limit_2",
    "hand_limit_1",
    "hand_limit_0",
    "keeper_limit_4",
    "keeper_limit_3",
    "keeper_limit_2",
    "draw_5",
    "draw_4",
    "draw_2",
    "play_2",
    "draw_3",
    "play_4",
    "play_3",

    # Keepers
    "cat",
    "dog",
    "monkey",
    "horse",
    "cow",
    "sheep",
    "farmer",
    "grass",
    "field",
    "fire",
    "wood",
    "rain",
    "sunshine",
    "book",
    "map",
    "key",
    "excalibur",
    "air",
    "the_void",

    # Goals
    "the_farm",
    "tending_the_flock",
    "dairy_farm",
    "plowing",
    "pasture",
    "cows_in_the_field",
    "open_range",
    "grazing_sheep",
    "growing_grass",
    "key_lost_in_the_grass",
    "sheepdog",
    "milking_in_the_sun",
    "galloping_on_air",
    "rainbow",
    "cat_in_the_rain",
    "sunbathing_cat",
    "reading_dog",
    "treasure_map",
    "reading_by_fire",
    "curious_monkey",
    "cartographer",
    "skymap",
    "campfire",
    "tree_climber",
    "sword_in_the_stone",
    "farmer_and_an_animal",
    "all_the_animals",
    "nothingness",

    # New action cards
    "pandoras_box",
    "rewind",
    "robin_hood",
    "time_vortex",
    "gift_giveaway",
    "dig_up_the_past",
    "space_jackpot",
    "supernova",
    "destroy_all_keepers",
    "roll_for_it",
    "close_enough",
    "rough_seas",
    "brain_drain",
    "oops",

    # New rule cards
    "triple_agenda",
    "card_transfusion",
    "plunder",

    # Action cards from base deck
    "zap_a_card",
    "trash_a_keeper",
    "draw_3_play_2_of_them",
    "jackpot",
    "exchange_keepers",
    "lets_simplify",
    "lets_do_that_again",
    "trade_hands",
    "no_limits",
    "take_another_turn",
    "discard_and_draw",
    
    # Rule cards from base deck
    "double_agenda",
    "recycling",
    "goal_mill",
    "no_hand_bonus",
    "party_bonus",
    "poor_bonus",
    "rich_bonus",
    "swap_plays_for_draws",
    "get_on_with_it",

    # Goal cards from base deck
    "5_keepers",
    "10_cards_in_hand",

]

simple_fluxx_deck = [
    # Rules - Draw/Play/Limits
    "hand_limit_2",
    "hand_limit_1",
    "hand_limit_0",
    "keeper_limit_4",
    "keeper_limit_3",
    "keeper_limit_2",
    "draw_5",
    "draw_4",
    "draw_2",
    "play_2",
    "draw_3",
    "play_4",
    "play_3",

    # Keepers
    "the_sun",
    "the_party",
    "music",
    "dreams",
    "love",
    "peace",
    "sleep",
    "the_brain",
    "bread",
    "chocolate",
    "cookies",
    "milk",
    "time",
    "money",
    "the_eye",
    "the_moon",
    "the_rocket",
    "the_toaster",
    "television",

    # Goals
    "the_appliances",
    "baked_goods",
    "bed_time",
    "bread_and_chocolate",
    "cant_buy_me_love",
    "chocolate_cookies",
    "chocolate_milk",
    "day_dreams",
    "dreamland",
    "the_eye_of_the_beholder",
    "great_theme_song",
    "hearts_and_minds",
    "hippyism",
    "lullaby",
    "milk_and_cookies",
    "the_minds_eye",
    "night_and_day",
    "party_time",
    "rocket_science",
    "rocket_to_the_moon",
    "squishy_chocolate",
    "time_is_money",
    "toast",
    "turn_it_up",
    "winning_the_lottery",
    "world_peace",
    "5_keepers",
    "10_cards_in_hand",
    "the_brain_no_tv",
    "party_snacks",
]

base_deck = [
    # Rules - Draw/Play/Limits
    "hand_limit_2",
    "hand_limit_1",
    "hand_limit_0",
    "keeper_limit_4",
    "keeper_limit_3",
    "keeper_limit_2",
    "draw_5",
    "draw_4",
    "draw_2",
    "play_2",
    "draw_3",
    "play_4",
    "play_3",

    # Keepers
    "the_sun",
    "the_party",
    "music",
    "dreams",
    "love",
    "peace",
    "sleep",
    "the_brain",
    "bread",
    "chocolate",
    "cookies",
    "milk",
    "time",
    "money",
    "the_eye",
    "the_moon",
    "the_rocket",
    "the_toaster",
    "television",

    # Goals
    "the_appliances",
    "baked_goods",
    "bed_time",
    "bread_and_chocolate",
    "cant_buy_me_love",
    "chocolate_cookies",
    "chocolate_milk",
    "day_dreams",
    "dreamland",
    "the_eye_of_the_beholder",
    "great_theme_song",
    "hearts_and_minds",
    "hippyism",
    "lullaby",
    "milk_and_cookies",
    "the_minds_eye",
    "night_and_day",
    "party_time",
    "rocket_science",
    "rocket_to_the_moon",
    "squishy_chocolate",
    "time_is_money",
    "toast",
    "turn_it_up",
    "winning_the_lottery",
    "world_peace",
    "5_keepers",
    "10_cards_in_hand",
    "the_brain_no_tv",
    "party_snacks",

    # Actions
    "use_what_you_take",
    "zap_a_card",
    "trash_a_new_rule",
    "trash_a_keeper",
    "trade_hands",
    "todays_special",
    "draw_2_and_use_em",
    "draw_3_play_2_of_them",
    "steal_a_keeper",
    "share_the_wealth",
    "rules_reset",
    "rock_paper_scissors_showdown",
    "random_tax",
    "no_limits",
    "lets_simplify",
    "lets_do_that_again",
    "jackpot",
    "exchange_keepers",
    "empty_the_trash",
    "discard_and_draw",
    "take_another_turn",
    "rotate_hands",
    "everybody_gets_1",

    # Free Action/Complex Rules
    "mystery_play",
    "swap_plays_for_draws",
    "get_on_with_it",
    "recycling",
    "goal_mill",
    "play_all",
    "play_all_but_1",
    "no_hand_bonus",
    "party_bonus",
    "poor_bonus",
    "rich_bonus",
    "double_agenda",
    "first_play_random",
    "inflation",
]